---
- hosts: localhost
  connection: local
  become: true
  gather_facts: false

  vars:
    # (un)comment items to select the desired repositories
    repositories:
      - stable
      # - nightly
      # - test

  pre_tasks:
    - name: install-engine-apt | Determine name of Debian distribution
      shell: >
        [[ -e /etc/debian_version ]]
        && source /etc/os-release
        && echo ${DEBIAN_CODENAME:-$VERSION_CODENAME}
      args:
        executable: /bin/bash
      register: codename
      changed_when: false

    - name: install-engine-apt | Determine architecture packages are installed for
      command: dpkg --print-architecture
      register: arch
      changed_when: false

  tasks:
    - name: install-engine-apt | Uninstall old versions
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: install-engine-apt | Import key
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/debian/gpg

    - name: install-engine-apt | Add repository
      apt_repository:
        repo: >
          deb [arch={{ arch.stdout }}] https://download.docker.com/linux/debian
          {{ codename.stdout }} {{ repositories | join(' ') }}
        filename: docker

    - name: install-engine-apt | Install packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true

    - name: install-engine-apt | Start and enable service
      service:
        name: docker
        state: started
        enabled: true

    - name: install-engine-apt | Add current user to group
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups:
          - docker
        append: true

# vim: et sw=2 ts=2
